openapi: 3.0.4
info:
  title: Stock Market Open Times
  description: Stock Market Open Times is a simple tool for getting the open times of the stock market. It returns the open times of the stock market for each day of the week.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/stockmarketopentimes:
    get:
      summary: Lookup Market Open Times
      description: Stock Market Open Times is a simple tool for getting the open times of the stock market. It returns the open times of the stock market for each day of the week.
      operationId: stockmarketopentimes
      parameters:
      - name: exchange
        in: query
        schema:
          type: string
        required: true
        description: The stock exchange for which you want to get the open times (e.g. NYSE, NASDAQ, BATS, CHX, PHLX, AMEX, ARCA, ISE, CBOE, LSE, FWB, TSE, HKEX, ASX, BSE, JSE, SSE, SZSE, SGX, EURONEXT, TSX, MOEX, SIX, BIST, JPX, KRX, IDX, SET, MYX, TWSE, HOSE, DFM, ADX, QSE, EGX, BCB, BVSP, BVC, BMV, KSE, TAWUDAL)
        example: nyse
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  timezone: America/New_York
                  exchange: NYSE
                  fullName: New York Stock Exchange
                  isOpen: false
                  openingTime: 2025-02-20 09:30:00
                  closingTime: 2025-02-20 16:00:00
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
